### ISSUE TITLE
No longer works :(

### ISSUE THREAD

**Issue by hirowa** [GewoonJaap/WinWhisper#10]
I've tried multiple things:
- Default srt location + 1 video
- Default srt location + folder path with 3 videos
- Folder path for srt location + 1 video
- Folder path for srt location + folder path with 3 videos

Used both versions
- Standalone Zip file 
- Setup.exe

And I always get the following error, and the the terminal closes itself.
I've checked the model is indeed in the rgith folder, so I don't know what's wrong :(

![Untitled](https://github.com/GewoonJaap/WinWhisper/assets/42184093/e929a393-7538-4d59-afa5-1ebea901e94d)

**Comment by GewoonJaap** [comment]
:( I am going to investigate. As far as I know I haven't touched a single line of code regarding the whisperAI it self. Will try to reproduce this error on my end and fix it.

**Comment by hirowa** [comment]
Found the problem, it appears this instance doesn't like to wait to download the model heheh (it downloaded only 25mb/145mb), so I copied the previous model into the new folder and it works!

The problem I have now is that even if I set up a custom output folder it still output in the default system folder.

**Comment by GewoonJaap** [comment]
Ohh, thanks! I might know what the issue is then. It probably is downloading and already starts a new video to process, which then thinks the model already exists

**Comment by GewoonJaap** [comment]
Will fix both errors probably tomorrow or Saturday. If you see any other bugs please send them to me so I can patch those as well :)

**Comment by hirowa** [comment]
Thank you so much for your hard work! Will do! :)

**Comment by GewoonJaap** [comment]
I have fixed the model loading issue, sadly I am not able to replicate the outputFolder issue. I do have added logging in case the outputFolder isn't valid.

I tried manually copy and pasting the output path as well as dragging the folder into the terminal window. Both worked fine

**Comment by GewoonJaap** [comment]
I am closing this issue due to inactivity. Feel free to re-open when necessary

**Comment by hirowa** [comment]
Hi, sorry, was really busy, the folder issue still persist for me. I've deleted previous versions and cleaned the %appdata% local folder. So I don't know what I'm doing wrong. (See video)
---
I discovered that If I manually delete the quotation marks it works as intended! Is there a way to allow it to have quotation marks?
Maybe something like `directory = input("Please enter the folder path: ").strip('"')`

https://github.com/GewoonJaap/WinWhisper/assets/42184093/fc2011d8-c98f-48d4-bd12-885ca31c32fc

**Comment by GewoonJaap** [comment]
Aha, I forgot to test the edge case where folders have spaces in them thus causing " to be inserted. Will patch this :)

**Comment by hirowa** [comment]
Thanks!

**Comment by GewoonJaap** [comment]
This has been fixed in V1.3.1, which is published :)

**Comment by hirowa** [comment]
Thank you, you're amazing, works like a charm :)

**Comment by GewoonJaap** [comment]
Great to hear it works amazing! Thanks for using the application and helping me make it better :)
